// frontend/src/components/admin/EditParkingInfoDialog.vue
<template>
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
    <div class="bg-white rounded-lg p-6 w-full max-w-md">
      <h2 class="text-xl font-bold mb-4">Editar Información del Estacionamiento</h2>
      
      <form @submit.prevent="handleSubmit">
        <div class="space-y-4">
          <div>
            <label class="block text-sm font-medium mb-1">Nombre</label>
            <input
              v-model="form.name"
              type="text"
              class="w-full p-2 border rounded"
              required
            />
          </div>

          <div>
            <label class="block text-sm font-medium mb-1">Ubicación</label>
            <input
              v-model="form.location"
              type="text"
              class="w-full p-2 border rounded"
              required
            />
          </div>

          <div>
            <label class="block text-sm font-medium mb-1">Imagen URL</label>
            <input
              v-model="form.image"
              type="url"
              class="w-full p-2 border rounded"
              required
            />
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium mb-1">Tarifa Auto</label>
              <input
                v-model="form.rates.auto"
                type="number"
                min="0"
                step="0.01"
                class="w-full p-2 border rounded"
                required
              />
            </div>
            <div>
              <label class="block text-sm font-medium mb-1">Tarifa Moto</label>
              <input
                v-model="form.rates.moto"
                type="number"
                min="0"
                step="0.01"
                class="w-full p-2 border rounded"
                required
              />
            </div>
          </div>
        </div>

        <div class="mt-6 flex justify-end space-x-3">
          <Button variant="outline" type="button" @click="$emit('close')">
            Cancelar
          </Button>
          <Button type="submit">
            Guardar Cambios
          </Button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import Button from '../ui/Button.vue';

export default {
  name: 'EditParkingInfoDialog',
  
  components: {
    Button,
  },

  props: {
    parking: {
      type: Object,
      required: true,
    },
  },

  emits: ['close', 'update'],

  setup(props, { emit }) {
    const form = ref({
      name: props.parking.name,
      location: props.parking.location,
      image: props.parking.image,
      rates: {
        auto: props.parking.rates?.auto || 0,
        moto: props.parking.rates?.moto || 0,
      },
    });

    const handleSubmit = async () => {
      try {
        // Aquí implementaremos la llamada a la API
        // const response = await fetch(`/api/parkings/${props.parking.id}`, {
        //   method: 'PUT',
        //   headers: { 'Content-Type': 'application/json' },
        //   body: JSON.stringify(form.value),
        // });
        // const updatedParking = await response.json();
        
        emit('update', form.value);
      } catch (error) {
        console.error('Error al actualizar el estacionamiento:', error);
      }
    };

    return {
      form,
      handleSubmit,
    };
  },
};
</script>

// frontend/Admin Dashboard Prototype/src/components/EditParkingInfoDialog.tsx
import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "./ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Textarea } from "./ui/textarea";
import { Separator } from "./ui/separator";
import { toast } from "sonner@2.0.3";

interface Parking {
  id: string;
  name: string;
  image: string;
  location: string;
  spaces: number;
  occupiedSpaces: number;
  rates: {
    moto: number;
    auto: number;
  };
  employees: number;
  revenue: number;
}

interface EditParkingInfoDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  parking: Parking;
  onSave: (updatedParking: Parking) => void;
}

export function EditParkingInfoDialog({ 
  open, 
  onOpenChange, 
  parking, 
  onSave 
}: EditParkingInfoDialogProps) {
  const [formData, setFormData] = useState({
    name: parking.name,
    location: parking.location,
    rates: {
      moto: parking.rates.moto.toString(),
      auto: parking.rates.auto.toString()
    }
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const updatedParking = {
      ...parking,
      name: formData.name,
      location: formData.location,
      rates: {
        moto: parseFloat(formData.rates.moto),
        auto: parseFloat(formData.rates.auto)
      }
    };

    onSave(updatedParking);
    onOpenChange(false);
    
    toast.success("Información actualizada correctamente", {
      description: "Los cambios han sido guardados exitosamente."
    });
  };

  const handleCancel = () => {
    // Resetear formulario
    setFormData({
      name: parking.name,
      location: parking.location,
      rates: {
        moto: parking.rates.moto.toString(),
        auto: parking.rates.auto.toString()
      }
    });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="text-2xl text-slate-800 flex items-center gap-2">
            Editar Información del Estacionamiento
          </DialogTitle>
          <DialogDescription>
            Modifica la información básica y las tarifas del estacionamiento.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Información Básica */}
          <div className="space-y-4">
            <h3 className="text-lg text-blue-800 border-b border-blue-200 pb-2">
              Información Básica
            </h3>
            
            <div className="space-y-2">
              <Label htmlFor="name">Nombre del Estacionamiento</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                className="border-blue-200 focus:border-blue-400"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="location">Ubicación</Label>
              <Textarea
                id="location"
                value={formData.location}
                onChange={(e) => setFormData(prev => ({ ...prev, location: e.target.value }))}
                className="border-blue-200 focus:border-blue-400"
                rows={3}
                required
              />
            </div>
          </div>

          <Separator className="bg-blue-200" />

          {/* Tarifas */}
          <div className="space-y-4">
            <h3 className="text-lg text-green-800 border-b border-green-200 pb-2">
              Tarifas por Hora
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="rate-moto">Tarifa Moto (por hora)</Label>
                <div className="relative">
                  <span className="absolute left-3 top-3 text-green-600">$</span>
                  <Input
                    id="rate-moto"
                    type="number"
                    step="0.01"
                    min="0"
                    value={formData.rates.moto}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      rates: { ...prev.rates, moto: e.target.value }
                    }))}
                    className="pl-8 border-green-200 focus:border-green-400"
                    required
                  />
                </div>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="rate-auto">Tarifa Auto (por hora)</Label>
                <div className="relative">
                  <span className="absolute left-3 top-3 text-green-600">$</span>
                  <Input
                    id="rate-auto"
                    type="number"
                    step="0.01"
                    min="0"
                    value={formData.rates.auto}
                    onChange={(e) => setFormData(prev => ({
                      ...prev,
                      rates: { ...prev.rates, auto: e.target.value }
                    }))}
                    className="pl-8 border-green-200 focus:border-green-400"
                    required
                  />
                </div>
              </div>
            </div>

            {/* Vista previa de ingresos */}
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <h4 className="text-green-800 mb-2">Vista Previa de Ingresos Estimados</h4>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                <div className="text-center">
                  <div className="text-lg text-green-600">
                    ${((parseFloat(formData.rates.auto) || 0) * 8 + (parseFloat(formData.rates.moto) || 0) * 8).toLocaleString()}
                  </div>
                  <p className="text-green-700">Por día</p>
                </div>
                <div className="text-center">
                  <div className="text-lg text-green-600">
                    ${(((parseFloat(formData.rates.auto) || 0) * 8 + (parseFloat(formData.rates.moto) || 0) * 8) * 7).toLocaleString()}
                  </div>
                  <p className="text-green-700">Por semana</p>
                </div>
                <div className="text-center">
                  <div className="text-lg text-green-600">
                    ${(((parseFloat(formData.rates.auto) || 0) * 8 + (parseFloat(formData.rates.moto) || 0) * 8) * 30).toLocaleString()}
                  </div>
                  <p className="text-green-700">Por mes</p>
                </div>
              </div>
            </div>
          </div>

          {/* Botones de Acción */}
          <div className="flex gap-4 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={handleCancel}
              className="flex-1 border-gray-300 text-gray-700 hover:bg-gray-50"
            >
              Cancelar
            </Button>
            <Button
              type="submit"
              className="flex-1 bg-gradient-to-r from-blue-600 to-green-600 hover:from-blue-700 hover:to-green-700"
            >
              Guardar Cambios
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
