// frontend/src/components/admin/ParkingDetailView.vue
<template>
  <div class="h-full">
    <!-- Header con navegación -->
    <div class="bg-gradient-to-r from-gray-100 to-gray-200 border-b border-gray-300">
      <div class="max-w-7xl mx-auto px-4 py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-4">
            <button class="flex items-center text-gray-600 hover:text-gray-800" @click="$router.back()">
              <ChevronLeft class="w-5 h-5 mr-1" />
              <span class="text-sm font-medium">Volver al Dashboard</span>
            </button>
          </div>
          <div class="flex items-center space-x-3">
            <Button @click="showEditDialog = true" variant="outline" class="flex items-center">
              <Edit2 class="w-4 h-4 mr-2" />
              Editar Información
            </Button>
            <Button @click="showDeleteDialog = true" variant="destructive" class="flex items-center">
              <Trash2 class="w-4 h-4 mr-2" />
              Eliminar Estacionamiento
            </Button>
          </div>
        </div>
      </div>
    </div>

    <!-- Información del estacionamiento -->
    <div class="bg-gray-100 border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 py-6">
        <h1 class="text-2xl font-bold text-gray-900">{{ parking.name }}</h1>
        <p class="mt-1 text-sm text-gray-600">{{ parking.location }}</p>
      </div>
    </div>

    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <Card class="bg-gradient-to-r from-[hsl(var(--info))] to-[hsl(var(--info)_/_0.8)] text-white">
          <CardContent class="flex items-center justify-between p-6">
            <div>
              <p class="text-sm font-medium text-white/90">Plazas Ocupadas</p>
              <h3 class="text-2xl font-bold mt-2">{{ parking.occupiedSpaces }}/{{ parking.spaces }}</h3>
            </div>
            <div class="bg-white/20 p-3 rounded-lg">
              <Car class="w-6 h-6 text-white" />
            </div>
          </CardContent>
        </Card>

        <Card class="bg-gradient-to-r from-[hsl(var(--success))] to-[hsl(var(--success)_/_0.8)] text-white">
          <CardContent class="flex items-center justify-between p-6">
            <div>
              <p class="text-sm font-medium text-white/90">Tasa de Ocupación</p>
              <h3 class="text-2xl font-bold mt-2">{{ Math.round((parking.occupiedSpaces / parking.spaces) * 100) }}%</h3>
            </div>
            <div class="bg-white/20 p-3 rounded-lg">
              <TrendingUp class="w-6 h-6 text-white" />
            </div>
          </CardContent>
        </Card>

        <Card class="bg-gradient-to-r from-[hsl(var(--primary))] to-[hsl(var(--primary)_/_0.8)] text-white">
          <CardContent class="flex items-center justify-between p-6">
            <div>
              <p class="text-sm font-medium text-white/90">Ingresos del Mes</p>
              <h3 class="text-2xl font-bold mt-2">{{ formatCurrency(parking.revenue) }}</h3>
            </div>
            <div class="bg-white/20 p-3 rounded-lg">
              <DollarSign class="w-6 h-6 text-white" />
            </div>
          </CardContent>
        </Card>

        <Card class="bg-gradient-to-r from-[hsl(var(--warning))] to-[hsl(var(--warning)_/_0.8)] text-white">
          <CardContent class="flex items-center justify-between p-6">
            <div>
              <p class="text-sm font-medium text-white/90">Empleados</p>
              <h3 class="text-2xl font-bold mt-2">{{ parking.employees }}</h3>
            </div>
            <div class="bg-white/20 p-3 rounded-lg">
              <Users class="w-6 h-6 text-white" />
            </div>
          </CardContent>
        </Card>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        <Card class="p-6">
          <CardHeader class="px-0 pt-0">
            <CardTitle class="text-lg font-semibold text-gray-900">Ocupación Semanal</CardTitle>
          </CardHeader>
          <CardContent class="px-0 pb-0">
            <div class="h-[300px]">
              <BarChart :data="weeklyOccupancyData" />
            </div>
          </CardContent>
        </Card>

        <Card class="p-6">
          <CardHeader class="px-0 pt-0">
            <CardTitle class="text-lg font-semibold text-gray-900">Distribución por Tipo</CardTitle>
          </CardHeader>
          <CardContent class="px-0 pb-0">
            <div class="h-[300px]">
              <PieChart :data="occupancyTypeData" />
            </div>
          </CardContent>
        </Card>
      </div>

      <Card class="p-6 mb-8">
        <CardHeader class="px-0 pt-0">
          <CardTitle class="text-lg font-semibold text-gray-900">Ingresos Mensuales</CardTitle>
        </CardHeader>
        <CardContent class="px-0 pb-0">
          <div class="h-[300px]">
            <LineChart :data="monthlyRevenueData" />
          </div>
        </CardContent>
      </Card>

      <Tabs class="col-span-2" defaultValue="statistics">
        <TabsList>
          <TabsTrigger value="statistics">Estadísticas</TabsTrigger>
          <TabsTrigger value="spaces">Espacios</TabsTrigger>
          <TabsTrigger value="employees">Empleados</TabsTrigger>
        </TabsList>

        <TabsContent value="statistics">
          <div class="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Ocupación por Hora</CardTitle>
              </CardHeader>
              <CardContent>
                <LineChart :data="hourlyOccupancy" />
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Ingresos por Día</CardTitle>
              </CardHeader>
              <CardContent>
                <BarChart :data="dailyRevenue" />
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="spaces">
          <Card>
            <CardHeader class="flex flex-row items-center justify-between">
              <CardTitle>Gestión de Espacios</CardTitle>
              <Button @click="showSpacesDialog = true">
                <i class="fas fa-plus mr-2"></i> Agregar Espacio
              </Button>
            </CardHeader>
            <CardContent>
              <!-- Tabla de espacios -->
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="employees">
          <Card>
            <CardHeader class="flex flex-row items-center justify-between">
              <CardTitle>Gestión de Empleados</CardTitle>
              <Button @click="showEmployeesDialog = true">
                <i class="fas fa-plus mr-2"></i> Agregar Empleado
              </Button>
            </CardHeader>
            <CardContent>
              <!-- Tabla de empleados -->
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>

    <EditParkingInfoDialog
      v-if="showEditDialog"
      :parking="parking"
      @close="showEditDialog = false"
      @update="updateParking"
    />

    <ManageEmployeesDialog
      v-if="showEmployeesDialog"
      :parking-id="parking.id"
      @close="showEmployeesDialog = false"
    />

    <ManageSpacesDialog
      v-if="showSpacesDialog"
      :parking-id="parking.id"
      @close="showSpacesDialog = false"
    />

    <DeleteParkingDialog
      v-if="showDeleteDialog"
      :parking-id="parking.id"
      @close="showDeleteDialog = false"
      @delete="deleteParking"
    />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { Car, TrendingUp, DollarSign, Users, ChevronLeft, Edit2, Trash2 } from 'lucide-vue-next'
import Card from '../ui/Card.vue'
import CardHeader from '../ui/CardHeader.vue'
import CardTitle from '../ui/CardTitle.vue'
import CardContent from '../ui/CardContent.vue'
import Button from '../ui/Button.vue'
import Tabs from '../ui/Tabs.vue'
import TabsList from '../ui/TabsList.vue'
import TabsTrigger from '../ui/TabsTrigger.vue'
import TabsContent from '../ui/TabsContent.vue'
import LineChart from '../ui/LineChart.vue'
import BarChart from '../ui/BarChart.vue'
import PieChart from '../ui/PieChart.vue'

import EditParkingInfoDialog from './EditParkingInfoDialog.vue'
import ManageEmployeesDialog from './ManageEmployeesDialog.vue'
import ManageSpacesDialog from './ManageSpacesDialog.vue'
import DeleteParkingDialog from './DeleteParkingDialog.vue'

export default {
  name: 'ParkingDetailView',
  
  components: {
    Card,
    CardHeader,
    CardTitle,
    CardContent,
    Button,
    Tabs,
    TabsList,
    TabsTrigger,
    TabsContent,
    LineChart,
    BarChart,
    PieChart,
    EditParkingInfoDialog,
    ManageEmployeesDialog,
    ManageSpacesDialog,
    DeleteParkingDialog,
  },

  setup() {
    const parking = ref({
      id: '1',
      name: 'Estacionamiento Centro',
      image: '/parking-image.jpg',
      location: 'Av. Corrientes 1234, CABA',
      spaces: 120,
      occupiedSpaces: 98,
      employees: 4,
      revenue: 67000,
    });

    const weeklyOccupancyData = ref({
      labels: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab', 'Dom'],
      datasets: [
        {
          label: 'Ocupación',
          data: [65, 80, 75, 90, 95, 40, 35],
          backgroundColor: '#3b82f6',
        }
      ]
    });

    const occupancyTypeData = ref({
      labels: ['Autos', 'Motos'],
      datasets: [
        {
          data: [70, 30],
          backgroundColor: ['#3b82f6', '#22c55e'],
        }
      ]
    });

    const monthlyRevenueData = ref({
      labels: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun'],
      datasets: [
        {
          label: 'Ingresos Mensuales',
          data: [45000, 48000, 52000, 49000, 67000, 65000],
          borderColor: '#8b5cf6',
          tension: 0.3,
          fill: false
        }
      ]
    });

    const showEditDialog = ref(false);
    const showEmployeesDialog = ref(false);
    const showSpacesDialog = ref(false);
    const showDeleteDialog = ref(false);
    
    const hourlyOccupancy = ref([]);
    const dailyRevenue = ref([]);

    onMounted(() => {
      hourlyOccupancy.value = [
        { hour: '08:00', value: 10 },
        { hour: '09:00', value: 15 },
        { hour: '10:00', value: 20 },
        { hour: '11:00', value: 25 },
        { hour: '12:00', value: 30 },
      ];

      dailyRevenue.value = [
        { day: 'Lunes', value: 5000 },
        { day: 'Martes', value: 6000 },
        { day: 'Miércoles', value: 4500 },
        { day: 'Jueves', value: 7000 },
        { day: 'Viernes', value: 8000 },
      ];
    });

    const updateParking = (updatedData) => {
      Object.assign(parking.value, updatedData);
      showEditDialog.value = false;
    };

    const deleteParking = () => {
      showDeleteDialog.value = false;
      // Implementar redirección o eliminación aquí
    };

    const formatCurrency = (value) => {
      return new Intl.NumberFormat('es-AR', {
        style: 'currency',
        currency: 'ARS'
      }).format(value);
    };

    return {
      parking,
      weeklyOccupancyData,
      occupancyTypeData,
      monthlyRevenueData,
      showEditDialog,
      showEmployeesDialog,
      showSpacesDialog,
      showDeleteDialog,
      updateParking,
      deleteParking,
      formatCurrency,
      hourlyOccupancy,
      dailyRevenue,
    };
  },
};
</script>

<style scoped>
.container {
  max-width: 1200px;
}
</style>

// frontend/Admin Dashboard Prototype/src/components/ParkingDetailView.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { 
  ArrowLeft, 
  Users, 
  Car, 
  Bike, 
  DollarSign, 
  TrendingUp,
  Edit,
  Trash2,
  Plus,
  Calendar
} from "lucide-react";
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell
} from 'recharts';
import { EditParkingInfoDialog } from "./EditParkingInfoDialog";
import { ManageEmployeesDialog } from "./ManageEmployeesDialog";
import { ManageSpacesDialog } from "./ManageSpacesDialog";
import { DeleteParkingDialog } from "./DeleteParkingDialog";
import { ImageWithFallback } from "./figma/ImageWithFallback";

interface Parking {
  id: string;
  name: string;
  image: string;
  location: string;
  spaces: number;
  occupiedSpaces: number;
  rates: {
    moto: number;
    auto: number;
  };
  employees: number;
  revenue: number;
}

interface ParkingDetailViewProps {
  parking: Parking;
  onBack: () => void;
  onUpdate: (updatedParking: Parking) => void;
  onDelete: (parkingId: string) => void;
}

export function ParkingDetailView({ parking, onBack, onUpdate, onDelete }: ParkingDetailViewProps) {
  const [showEditInfo, setShowEditInfo] = useState(false);
  const [showManageEmployees, setShowManageEmployees] = useState(false);
  const [showManageSpaces, setShowManageSpaces] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);

  // Datos simulados para gráficos
  const weeklyOccupancyData = [
    { day: 'Lun', autos: 45, motos: 23, total: 68 },
    { day: 'Mar', autos: 52, motos: 28, total: 80 },
    { day: 'Mié', autos: 48, motos: 25, total: 73 },
    { day: 'Jue', autos: 61, motos: 32, total: 93 },
    { day: 'Vie', autos: 67, motos: 35, total: 102 },
    { day: 'Sáb', autos: 39, motos: 18, total: 57 },
    { day: 'Dom', autos: 31, motos: 14, total: 45 }
  ];

  const revenueData = [
    { month: 'Ene', ingresos: 45000 },
    { month: 'Feb', ingresos: 52000 },
    { month: 'Mar', ingresos: 48000 },
    { month: 'Abr', ingresos: 61000 },
    { month: 'May', ingresos: 67000 },
    { month: 'Jun', ingresos: 59000 }
  ];

  const vehicleTypeData = [
    { name: 'Autos', value: 70, color: '#3b82f6' },
    { name: 'Motos', value: 30, color: '#10b981' }
  ];

  const occupancyRate = Math.round((parking.occupiedSpaces / parking.spaces) * 100);
  const availableSpaces = parking.spaces - parking.occupiedSpaces;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-green-50 to-blue-50">
      <div className="max-w-7xl mx-auto p-8 space-y-8">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="outline"
              onClick={onBack}
              className="flex items-center gap-2 border-blue-200 text-blue-700 hover:bg-blue-50"
            >
              <ArrowLeft className="w-4 h-4" />
              Volver al Dashboard
            </Button>
            <div>
              <h1 className="text-3xl text-slate-800">{parking.name}</h1>
              <p className="text-slate-600">{parking.location}</p>
            </div>
          </div>
          
          <div className="flex gap-3">
            <Button
              variant="outline"
              onClick={() => setShowEditInfo(true)}
              className="border-green-200 text-green-700 hover:bg-green-50"
            >
              <Edit className="w-4 h-4 mr-2" />
              Editar Información
            </Button>
            <Button
              variant="destructive"
              onClick={() => setShowDeleteDialog(true)}
            >
              <Trash2 className="w-4 h-4 mr-2" />
              Eliminar Estacionamiento
            </Button>
          </div>
        </div>

        {/* Imagen del estacionamiento */}
        <Card className="overflow-hidden shadow-xl border-0">
          <div className="relative h-64">
            <ImageWithFallback
              src={parking.image}
              alt={parking.name}
              className="w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
            <div className="absolute bottom-4 left-4 text-white">
              <h2 className="text-2xl mb-2">{parking.name}</h2>
              <div className="flex gap-4">
                <Badge className="bg-white/20 text-white hover:bg-white/30">
                  {parking.spaces} plazas totales
                </Badge>
                <Badge className="bg-white/20 text-white hover:bg-white/30">
                  {parking.occupiedSpaces} ocupadas
                </Badge>
                <Badge className="bg-white/20 text-white hover:bg-white/30">
                  {occupancyRate}% ocupación
                </Badge>
              </div>
            </div>
          </div>
        </Card>

        {/* KPIs principales */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="shadow-lg border-0 bg-gradient-to-r from-blue-500 to-blue-600 text-white">
            <CardContent className="p-6 flex items-center gap-4">
              <div className="p-3 bg-white/20 rounded-full">
                <Users className="w-6 h-6" />
              </div>
              <div>
                <p className="text-blue-100">Plazas Ocupadas</p>
                <p className="text-2xl">{parking.occupiedSpaces}/{parking.spaces}</p>
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-lg border-0 bg-gradient-to-r from-green-500 to-green-600 text-white">
            <CardContent className="p-6 flex items-center gap-4">
              <div className="p-3 bg-white/20 rounded-full">
                <TrendingUp className="w-6 h-6" />
              </div>
              <div>
                <p className="text-green-100">Tasa de Ocupación</p>
                <p className="text-2xl">{occupancyRate}%</p>
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-lg border-0 bg-gradient-to-r from-purple-500 to-purple-600 text-white">
            <CardContent className="p-6 flex items-center gap-4">
              <div className="p-3 bg-white/20 rounded-full">
                <DollarSign className="w-6 h-6" />
              </div>
              <div>
                <p className="text-purple-100">Ingresos del Mes</p>
                <p className="text-2xl">${parking.revenue.toLocaleString()}</p>
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-lg border-0 bg-gradient-to-r from-orange-500 to-orange-600 text-white">
            <CardContent className="p-6 flex items-center gap-4">
              <div className="p-3 bg-white/20 rounded-full">
                <Users className="w-6 h-6" />
              </div>
              <div>
                <p className="text-orange-100">Empleados</p>
                <p className="text-2xl">{parking.employees}</p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Pestañas principales */}
        <Tabs defaultValue="statistics" className="space-y-6">
          <TabsList className="grid w-full grid-cols-4 bg-white border border-blue-100">
            <TabsTrigger value="statistics" className="data-[state=active]:bg-blue-100 data-[state=active]:text-blue-700">
              Estadísticas
            </TabsTrigger>
            <TabsTrigger value="rates" className="data-[state=active]:bg-green-100 data-[state=active]:text-green-700">
              Tarifas
            </TabsTrigger>
            <TabsTrigger value="employees" className="data-[state=active]:bg-purple-100 data-[state=active]:text-purple-700">
              Empleados
            </TabsTrigger>
            <TabsTrigger value="spaces" className="data-[state=active]:bg-orange-100 data-[state=active]:text-orange-700">
              Gestión de Plazas
            </TabsTrigger>
          </TabsList>

          {/* Pestaña de Estadísticas */}
          <TabsContent value="statistics" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Gráfico de ocupación semanal */}
              <Card className="shadow-xl border-0">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-slate-800">
                    <Calendar className="w-5 h-5 text-blue-600" />
                    Ocupación Semanal
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="h-80">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={weeklyOccupancyData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                        <XAxis dataKey="day" stroke="#64748b" />
                        <YAxis stroke="#64748b" />
                        <Tooltip 
                          contentStyle={{
                            backgroundColor: 'white',
                            border: '1px solid #e2e8f0',
                            borderRadius: '8px'
                          }}
                        />
                        <Bar dataKey="autos" stackId="a" fill="#3b82f6" name="Autos" />
                        <Bar dataKey="motos" stackId="a" fill="#10b981" name="Motos" />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>

              {/* Distribución por tipo de vehículo */}
              <Card className="shadow-xl border-0">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-slate-800">
                    <Car className="w-5 h-5 text-green-600" />
                    Distribución por Tipo
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="h-80">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={vehicleTypeData}
                          cx="50%"
                          cy="50%"
                          outerRadius={100}
                          dataKey="value"
                          label={({ name, value }) => `${name}: ${value}%`}
                        >
                          {vehicleTypeData.map((entry, index) => (
                            <Cell key={`cell-${index}`} fill={entry.color} />
                          ))}
                        </Pie>
                        <Tooltip />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Gráfico de ingresos */}
            <Card className="shadow-xl border-0">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-slate-800">
                  <TrendingUp className="w-5 h-5 text-purple-600" />
                  Ingresos Mensuales
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-80">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={revenueData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                      <XAxis dataKey="month" stroke="#64748b" />
                      <YAxis stroke="#64748b" />
                      <Tooltip 
                        contentStyle={{
                          backgroundColor: 'white',
                          border: '1px solid #e2e8f0',
                          borderRadius: '8px'
                        }}
                        formatter={(value) => [`$${value.toLocaleString()}`, 'Ingresos']}
                      />
                      <Line 
                        type="monotone" 
                        dataKey="ingresos" 
                        stroke="#8b5cf6" 
                        strokeWidth={3}
                        dot={{ fill: '#8b5cf6', strokeWidth: 2, r: 6 }}
                      />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Pestaña de Tarifas */}
          <TabsContent value="rates" className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card className="shadow-xl border-0 border-l-4 border-l-blue-500">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-slate-800">
                    <Car className="w-5 h-5 text-blue-600" />
                    Tarifa para Autos
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="text-3xl text-blue-600">${parking.rates.auto}/hora</div>
                  <p className="text-slate-600">Tarifa actual para vehículos tipo auto</p>
                  <Button 
                    variant="outline" 
                    className="border-blue-200 text-blue-700 hover:bg-blue-50"
                    onClick={() => setShowEditInfo(true)}
                  >
                    <Edit className="w-4 h-4 mr-2" />
                    Modificar Tarifa
                  </Button>
                </CardContent>
              </Card>

              <Card className="shadow-xl border-0 border-l-4 border-l-green-500">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-slate-800">
                    <Bike className="w-5 h-5 text-green-600" />
                    Tarifa para Motos
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="text-3xl text-green-600">${parking.rates.moto}/hora</div>
                  <p className="text-slate-600">Tarifa actual para motocicletas</p>
                  <Button 
                    variant="outline" 
                    className="border-green-200 text-green-700 hover:bg-green-50"
                    onClick={() => setShowEditInfo(true)}
                  >
                    <Edit className="w-4 h-4 mr-2" />
                    Modificar Tarifa
                  </Button>
                </CardContent>
              </Card>
            </div>

            {/* Simulador de ingresos */}
            <Card className="shadow-xl border-0 bg-gradient-to-r from-purple-50 to-pink-50">
              <CardHeader>
                <CardTitle className="text-slate-800">Proyección de Ingresos</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="text-center space-y-2">
                    <div className="text-2xl text-purple-600">
                      ${((parking.rates.auto * 8 + parking.rates.moto * 8) * 30).toLocaleString()}
                    </div>
                    <p className="text-sm text-slate-600">Ingresos Mensuales Estimados</p>
                  </div>
                  <div className="text-center space-y-2">
                    <div className="text-2xl text-purple-600">
                      ${((parking.rates.auto * 8 + parking.rates.moto * 8) * 7).toLocaleString()}
                    </div>
                    <p className="text-sm text-slate-600">Ingresos Semanales Estimados</p>
                  </div>
                  <div className="text-center space-y-2">
                    <div className="text-2xl text-purple-600">
                      ${(parking.rates.auto * 8 + parking.rates.moto * 8).toLocaleString()}
                    </div>
                    <p className="text-sm text-slate-600">Ingresos Diarios Estimados</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Pestaña de Empleados */}
          <TabsContent value="employees" className="space-y-6">
            <Card className="shadow-xl border-0">
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-slate-800">
                  <Users className="w-5 h-5 text-purple-600" />
                  Gestión de Empleados
                </CardTitle>
                <Button
                  onClick={() => setShowManageEmployees(true)}
                  className="bg-purple-600 hover:bg-purple-700"
                >
                  <Plus className="w-4 h-4 mr-2" />
                  Gestionar Empleados
                </Button>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <div className="text-center p-6 bg-purple-50 rounded-lg border border-purple-100">
                    <div className="text-3xl text-purple-600 mb-2">{parking.employees}</div>
                    <p className="text-slate-600">Empleados Activos</p>
                  </div>
                  <div className="text-center p-6 bg-green-50 rounded-lg border border-green-100">
                    <div className="text-3xl text-green-600 mb-2">8</div>
                    <p className="text-slate-600">Horas Promedio</p>
                  </div>
                  <div className="text-center p-6 bg-blue-50 rounded-lg border border-blue-100">
                    <div className="text-3xl text-blue-600 mb-2">95%</div>
                    <p className="text-slate-600">Asistencia</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Pestaña de Gestión de Plazas */}
          <TabsContent value="spaces" className="space-y-6">
            <Card className="shadow-xl border-0">
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-slate-800">
                  <Car className="w-5 h-5 text-orange-600" />
                  Gestión de Plazas
                </CardTitle>
                <Button
                  onClick={() => setShowManageSpaces(true)}
                  className="bg-orange-600 hover:bg-orange-700"
                >
                  <Edit className="w-4 h-4 mr-2" />
                  Modificar Plazas
                </Button>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="text-center p-6 bg-blue-50 rounded-lg border border-blue-100">
                    <div className="text-3xl text-blue-600 mb-2">{parking.spaces}</div>
                    <p className="text-slate-600">Plazas Totales</p>
                  </div>
                  <div className="text-center p-6 bg-red-50 rounded-lg border border-red-100">
                    <div className="text-3xl text-red-600 mb-2">{parking.occupiedSpaces}</div>
                    <p className="text-slate-600">Plazas Ocupadas</p>
                  </div>
                  <div className="text-center p-6 bg-green-50 rounded-lg border border-green-100">
                    <div className="text-3xl text-green-600 mb-2">{availableSpaces}</div>
                    <p className="text-slate-600">Plazas Disponibles</p>
                  </div>
                  <div className="text-center p-6 bg-purple-50 rounded-lg border border-purple-100">
                    <div className="text-3xl text-purple-600 mb-2">{occupancyRate}%</div>
                    <p className="text-slate-600">Ocupación</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Diálogos */}
        <EditParkingInfoDialog
          open={showEditInfo}
          onOpenChange={setShowEditInfo}
          parking={parking}
          onSave={onUpdate}
        />

        <ManageEmployeesDialog
          open={showManageEmployees}
          onOpenChange={setShowManageEmployees}
          parkingId={parking.id}
        />

        <ManageSpacesDialog
          open={showManageSpaces}
          onOpenChange={setShowManageSpaces}
          parking={parking}
          onSave={onUpdate}
        />

        <DeleteParkingDialog
          open={showDeleteDialog}
          onOpenChange={setShowDeleteDialog}
          parking={parking}
          onConfirm={() => onDelete(parking.id)}
        />
      </div>
    </div>
  );
}
