// frontend/Admin Dashboard Prototype/src/components/ProfileView.tsx
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { Badge } from "./ui/badge";
import { User, Mail, Phone, MapPin, Calendar, Edit } from "lucide-react";

export function ProfileView() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-blue-50">
      <div className="max-w-4xl mx-auto p-8 space-y-8">
        <div className="text-center space-y-2">
          <h1 className="text-3xl text-slate-800">Mi Perfil</h1>
          <p className="text-slate-600">Gestiona tu información personal y configuración de cuenta</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Información del Usuario */}
          <Card className="lg:col-span-2 shadow-xl border-0 bg-white">
            <CardHeader className="bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-t-lg">
              <CardTitle className="flex items-center gap-3">
                <User className="w-6 h-6" />
                Información Personal
              </CardTitle>
            </CardHeader>
            <CardContent className="p-8 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="firstName">Nombre</Label>
                  <Input
                    id="firstName"
                    defaultValue="Juan Carlos"
                    className="border-purple-200 focus:border-purple-400"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="lastName">Apellido</Label>
                  <Input
                    id="lastName"
                    defaultValue="González"
                    className="border-purple-200 focus:border-purple-400"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <div className="relative">
                  <Mail className="w-4 h-4 absolute left-3 top-3 text-purple-500" />
                  <Input
                    id="email"
                    type="email"
                    defaultValue="juan.gonzalez@email.com"
                    className="pl-10 border-purple-200 focus:border-purple-400"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="phone">Teléfono</Label>
                <div className="relative">
                  <Phone className="w-4 h-4 absolute left-3 top-3 text-purple-500" />
                  <Input
                    id="phone"
                    defaultValue="+54 11 1234-5678"
                    className="pl-10 border-purple-200 focus:border-purple-400"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="address">Dirección</Label>
                <div className="relative">
                  <MapPin className="w-4 h-4 absolute left-3 top-3 text-purple-500" />
                  <Input
                    id="address"
                    defaultValue="Av. Corrientes 1234, CABA"
                    className="pl-10 border-purple-200 focus:border-purple-400"
                  />
                </div>
              </div>

              <div className="flex justify-end">
                <Button className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700">
                  <Edit className="w-4 h-4 mr-2" />
                  Actualizar Información
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Tarjeta de Perfil */}
          <div className="space-y-6">
            <Card className="shadow-xl border-0 bg-white">
              <CardContent className="p-8 text-center space-y-6">
                <Avatar className="w-24 h-24 mx-auto border-4 border-purple-200">
                  <AvatarImage src="/placeholder-avatar.jpg" />
                  <AvatarFallback className="bg-gradient-to-r from-purple-100 to-blue-100 text-purple-700 text-xl">
                    JG
                  </AvatarFallback>
                </Avatar>
                
                <div>
                  <h3 className="text-xl text-slate-800">Juan Carlos González</h3>
                  <p className="text-slate-600">Administrador</p>
                </div>

                <Badge className="bg-green-100 text-green-700 hover:bg-green-200">
                  Cuenta Activa
                </Badge>

                <div className="flex items-center justify-center gap-2 text-sm text-slate-500">
                  <Calendar className="w-4 h-4" />
                  Miembro desde Enero 2024
                </div>
              </CardContent>
            </Card>

            {/* Estadísticas rápidas */}
            <Card className="shadow-xl border-0 bg-gradient-to-r from-purple-500 to-blue-500 text-white">
              <CardContent className="p-6">
                <div className="space-y-4">
                  <h4 className="text-center">Resumen de Actividad</h4>
                  <div className="space-y-3">
                    <div className="flex justify-between">
                      <span>Estacionamientos</span>
                      <span className="font-medium">3</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Plazas Totales</span>
                      <span className="font-medium">405</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Empleados</span>
                      <span className="font-medium">12</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/admin/ProfileView.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-blue-50 p-8">
    <div class="max-w-4xl mx-auto space-y-8">
      <!-- Header -->
      <div class="text-center space-y-2">
        <h1 class="text-3xl font-bold text-slate-800">Mi Perfil</h1>
        <p class="text-slate-600">Gestiona tu información personal y configuración de cuenta</p>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Información del Usuario -->
        <Card class="lg:col-span-2 shadow-xl border-0 bg-white">
          <CardHeader class="bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-t-lg">
            <div class="flex items-center gap-3">
              <User class="w-6 h-6" />
              <h2 class="text-xl font-bold">Información Personal</h2>
            </div>
          </CardHeader>
          <CardContent class="p-8 space-y-6">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div class="space-y-2">
                <Label for="firstName">Nombre</Label>
                <Input
                  id="firstName"
                  :value="userInfo.nombre"
                  class="border-purple-200 focus:border-purple-400"
                  readonly
                />
              </div>
              <div class="space-y-2">
                <Label for="lastName">Apellido</Label>
                <Input
                  id="lastName"
                  :value="userInfo.apellido"
                  class="border-purple-200 focus:border-purple-400"
                  readonly
                />
              </div>
            </div>

            <div class="space-y-2">
              <Label for="email">Email</Label>
              <div class="relative">
                <Mail class="w-4 h-4 absolute left-3 top-3 text-purple-500" />
                <Input
                  id="email"
                  type="email"
                  :value="userInfo.correo"
                  class="pl-10 border-purple-200 focus:border-purple-400"
                  readonly
                />
              </div>
            </div>

            <div class="space-y-2">
              <Label for="phone">Teléfono</Label>
              <div class="relative">
                <Phone class="w-4 h-4 absolute left-3 top-3 text-purple-500" />
                <Input
                  id="phone"
                  :value="userInfo.telefono || 'No especificado'"
                  class="pl-10 border-purple-200 focus:border-purple-400"
                  readonly
                />
              </div>
            </div>

            <div class="space-y-2">
              <Label for="address">Dirección</Label>
              <div class="relative">
                <MapPin class="w-4 h-4 absolute left-3 top-3 text-purple-500" />
                <Input
                  id="address"
                  :value="userInfo.direccion || 'No especificada'"
                  class="pl-10 border-purple-200 focus:border-purple-400"
                  readonly
                />
              </div>
            </div>

            <div class="flex justify-end">
              <Button class="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white">
                <Edit class="w-4 h-4 mr-2" />
                Actualizar Información
              </Button>
            </div>
          </CardContent>
        </Card>

        <!-- Tarjeta de Perfil -->
        <div class="space-y-6">
          <Card class="shadow-xl border-0 bg-white">
            <CardContent class="p-8 text-center space-y-6">
              <div class="w-24 h-24 mx-auto rounded-full bg-gradient-to-r from-purple-100 to-blue-100 flex items-center justify-center text-purple-700 text-2xl font-bold border-4 border-purple-200">
                {{ initials }}
              </div>
              
              <div>
                <h3 class="text-xl font-semibold text-slate-800">{{ userInfo.nombre }} {{ userInfo.apellido }}</h3>
                <p class="text-slate-600">Administrador</p>
              </div>

              <div class="inline-block px-4 py-1 rounded-full bg-green-100 text-green-700 text-sm font-medium">
                Cuenta Activa
              </div>

              <div class="flex items-center justify-center gap-2 text-sm text-slate-500">
                <Calendar class="w-4 h-4" />
                Miembro desde Enero 2024
              </div>
            </CardContent>
          </Card>

          <!-- Estadísticas rápidas -->
          <Card class="shadow-xl border-0 bg-gradient-to-r from-purple-500 to-blue-500 text-white">
            <CardContent class="p-6">
              <div class="space-y-4">
                <h4 class="text-center font-semibold">Resumen de Actividad</h4>
                <div class="space-y-3">
                  <div class="flex justify-between">
                    <span>Estacionamientos</span>
                    <span class="font-bold text-lg">3</span>
                  </div>
                  <div class="flex justify-between">
                    <span>Plazas Totales</span>
                    <span class="font-bold text-lg">405</span>
                  </div>
                  <div class="flex justify-between">
                    <span>Empleados</span>
                    <span class="font-bold text-lg">12</span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { User, Mail, Phone, MapPin, Calendar, Edit } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardContent from '@/components/ui/CardContent.vue'

// Obtener datos del usuario desde localStorage
const userInfo = computed(() => {
  const stored = localStorage.getItem('user')
  if (stored) {
    return JSON.parse(stored)
  }
  return {
    nombre: 'Admin',
    apellido: 'Principal',
    nombre_usuario: 'admin',
    correo: 'admin@smartpark.com',
    telefono: '',
    direccion: '',
    estado: 'activo'
  }
})

const initials = computed(() => {
  return `${userInfo.value.nombre[0]}${userInfo.value.apellido[0]}`.toUpperCase()
})
</script>
