// Dashboard Map Screen Design/src/components/VehicleManagement.tsx
import { Car, Bike, Plus, Settings } from 'lucide-react';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { useState } from 'react';
import { VehicleRegistrationForm } from './VehicleRegistrationForm';

interface Vehicle {
  id: string;
  type: 'auto' | 'moto';
  name: string;
  plate: string;
  model: string;
  image?: string;
}

interface VehicleManagementProps {
  onClose: () => void;
}

export function VehicleManagement({ onClose }: VehicleManagementProps) {
  // Datos simulados de vehículos registrados
  const [vehicles, setVehicles] = useState<Vehicle[]>([
    { id: '1', type: 'auto', name: 'Mi Auto', plate: 'ABC 123', model: 'Toyota Corolla 2020' },
    { id: '2', type: 'auto', name: 'Auto Familiar', plate: 'XYZ 789', model: 'Honda Civic 2019' },
    { id: '3', type: 'moto', name: 'Mi Moto', plate: 'MOT 456', model: 'Honda Wave 110' },
    { id: '4', type: 'auto', name: 'Auto Trabajo', plate: 'DEF 456', model: 'Ford Focus 2021' }
  ]);

  const [selectedFilter, setSelectedFilter] = useState<'auto' | 'moto'>('auto');
  const [showRegistrationForm, setShowRegistrationForm] = useState<'auto' | 'moto' | null>(null);
  const filteredVehicles = vehicles.filter(v => v.type === selectedFilter);

  const handleRegisterVehicle = (vehicleData: {
    name: string;
    plate: string;
    model: string;
    image?: string;
  }) => {
    const newVehicle: Vehicle = {
      id: Date.now().toString(),
      type: showRegistrationForm!,
      ...vehicleData
    };
    
    setVehicles(prev => [...prev, newVehicle]);
    setShowRegistrationForm(null);
    
    // Cambiar al filtro del vehículo recién registrado
    setSelectedFilter(showRegistrationForm!);
  };

  const VehicleCard = ({ vehicle }: { vehicle: Vehicle }) => (
    <Card className="p-4 bg-gradient-to-br from-muted/50 to-muted/30 border-2 hover:border-primary/30 transition-all duration-200 hover:shadow-md min-w-40 max-w-48">
      <div className="space-y-3">
        {/* Imagen del vehículo si existe */}
        {vehicle.image && (
          <div className="w-full h-24 rounded-lg overflow-hidden">
            <img 
              src={vehicle.image} 
              alt={vehicle.name}
              className="w-full h-full object-cover"
            />
          </div>
        )}
        
        <div className="flex items-center justify-between">
          {vehicle.type === 'auto' ? (
            <Car className="h-6 w-6 text-primary" />
          ) : (
            <Bike className="h-6 w-6 text-primary" />
          )}
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8 hover:bg-primary/10"
            onClick={() => console.log('Configurar vehículo', vehicle.id)}
          >
            <Settings className="h-4 w-4" />
          </Button>
        </div>
        
        <div className="space-y-1">
          <p className="font-medium">{vehicle.name}</p>
          <p className="text-sm text-muted-foreground font-mono">{vehicle.plate}</p>
          <p className="text-xs text-muted-foreground">{vehicle.model}</p>
        </div>
      </div>
    </Card>
  );

  // Si estamos mostrando el formulario de registro
  if (showRegistrationForm) {
    return (
      <VehicleRegistrationForm
        vehicleType={showRegistrationForm}
        onCancel={() => setShowRegistrationForm(null)}
        onRegister={handleRegisterVehicle}
      />
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="bg-gradient-to-r from-primary to-primary/90 text-white p-6 pb-8">
        <div className="flex items-center justify-between">
          <Button
            variant="ghost"
            onClick={onClose}
            className="text-white hover:bg-white/20 rounded-lg px-3 py-2"
          >
            ← Volver
          </Button>
          <h1 className="text-xl font-semibold">Mis Vehículos</h1>
          <div className="w-16"></div> {/* Spacer para centrar el título */}
        </div>
      </div>

      {/* Contenido */}
      <div className="p-6 space-y-8 -mt-4">
        {/* Filtros centralizados */}
        <div className="flex justify-center">
          <div className="flex bg-muted/50 rounded-2xl p-2 space-x-2">
            <Button
              variant={selectedFilter === 'auto' ? 'default' : 'ghost'}
              className={`h-14 px-8 rounded-xl flex items-center space-x-3 transition-all duration-200 ${
                selectedFilter === 'auto' 
                  ? 'bg-blue-500 hover:bg-blue-600 text-white shadow-md' 
                  : 'hover:bg-blue-50 text-blue-600'
              }`}
              onClick={() => setSelectedFilter('auto')}
            >
              <Car className="h-6 w-6" />
              <div className="text-left">
                <div className="font-medium">Autos</div>
                <div className="text-xs opacity-80">
                  {vehicles.filter(v => v.type === 'auto').length} registrado{vehicles.filter(v => v.type === 'auto').length !== 1 ? 's' : ''}
                </div>
              </div>
            </Button>
            
            <Button
              variant={selectedFilter === 'moto' ? 'default' : 'ghost'}
              className={`h-14 px-8 rounded-xl flex items-center space-x-3 transition-all duration-200 ${
                selectedFilter === 'moto' 
                  ? 'bg-green-500 hover:bg-green-600 text-white shadow-md' 
                  : 'hover:bg-green-50 text-green-600'
              }`}
              onClick={() => setSelectedFilter('moto')}
            >
              <Bike className="h-6 w-6" />
              <div className="text-left">
                <div className="font-medium">Motos</div>
                <div className="text-xs opacity-80">
                  {vehicles.filter(v => v.type === 'moto').length} registrado{vehicles.filter(v => v.type === 'moto').length !== 1 ? 's' : ''}
                </div>
              </div>
            </Button>
          </div>
        </div>

        {/* Sección de vehículos filtrados */}
        <div className="space-y-6">
          {/* Título de la sección actual */}
          <div className="text-center">
            <h2 className="text-xl font-semibold">
              {selectedFilter === 'auto' ? 'Mis Autos' : 'Mis Motos'}
            </h2>
            <p className="text-sm text-muted-foreground mt-1">
              {filteredVehicles.length} vehículo{filteredVehicles.length !== 1 ? 's' : ''} registrado{filteredVehicles.length !== 1 ? 's' : ''}
            </p>
          </div>

          {/* Botón registrar vehículo */}
          <div className="flex justify-center">
            <Button
              variant="outline"
              className={`h-14 px-6 border-2 border-dashed rounded-xl flex items-center space-x-3 transition-all duration-200 ${
                selectedFilter === 'auto' 
                  ? 'border-blue-300 text-blue-600 hover:bg-blue-50 hover:border-blue-400' 
                  : 'border-green-300 text-green-600 hover:bg-green-50 hover:border-green-400'
              }`}
              onClick={() => setShowRegistrationForm(selectedFilter)}
            >
              <Plus className="h-5 w-5" />
              <span>Registrar {selectedFilter === 'auto' ? 'un auto' : 'una moto'}</span>
            </Button>
          </div>

          {/* Grid de vehículos */}
          {filteredVehicles.length > 0 && (
            <div className="flex flex-wrap gap-4 justify-center">
              {filteredVehicles.map((vehicle) => (
                <VehicleCard key={vehicle.id} vehicle={vehicle} />
              ))}
            </div>
          )}

          {/* Mensaje cuando no hay vehículos */}
          {filteredVehicles.length === 0 && (
            <div className="text-center py-8">
              <div className={`w-16 h-16 mx-auto rounded-full flex items-center justify-center mb-4 ${
                selectedFilter === 'auto' ? 'bg-blue-100' : 'bg-green-100'
              }`}>
                {selectedFilter === 'auto' ? (
                  <Car className={`h-8 w-8 ${selectedFilter === 'auto' ? 'text-blue-600' : 'text-green-600'}`} />
                ) : (
                  <Bike className={`h-8 w-8 ${selectedFilter === 'auto' ? 'text-blue-600' : 'text-green-600'}`} />
                )}
              </div>
              <h3 className="font-medium mb-2">No tenés {selectedFilter === 'auto' ? 'autos' : 'motos'} registrados</h3>
              <p className="text-sm text-muted-foreground">
                Registrá {selectedFilter === 'auto' ? 'tu primer auto' : 'tu primera moto'} para comenzar a hacer reservas
              </p>
            </div>
          )}
        </div>

        {/* Información adicional */}
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
          <div className="space-y-2">
            <h3 className="font-medium text-amber-800">Información importante</h3>
            <ul className="text-sm text-amber-700 space-y-1">
              <li>• Podés registrar hasta 5 vehículos por cuenta</li>
              <li>• Los datos del vehículo son necesarios para las reservas</li>
              <li>• Mantené actualizada la información de tus vehículos</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/client/VehicleManagement.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
    <!-- Header -->
    <div class="bg-gradient-to-r from-blue-600 to-blue-700 text-white p-6 pb-8">
      <div class="flex items-center justify-between">
        <button
          @click="$emit('close')"
          class="text-white hover:bg-white/20 rounded-lg px-3 py-2 transition"
        >
          ← Volver
        </button>
        <h1 class="text-xl font-semibold">Mis Vehículos</h1>
        <div class="w-16"></div>
      </div>
    </div>

    <!-- Contenido -->
    <div class="p-6 space-y-8 -mt-4">
      <!-- Filtros centralizados -->
      <div class="flex justify-center">
        <div class="flex bg-white/80 backdrop-blur-sm rounded-2xl p-2 space-x-2 shadow-lg">
          <button
            @click="selectedFilter = 'auto'"
            :class="[
              'h-14 px-8 rounded-xl flex items-center space-x-3 transition-all duration-200',
              selectedFilter === 'auto'
                ? 'bg-blue-500 text-white shadow-md'
                : 'hover:bg-blue-50 text-blue-600'
            ]"
          >
            <Car class="h-6 w-6" />
            <div class="text-left">
              <div class="font-medium">Autos</div>
              <div class="text-xs opacity-80">
                {{ vehicles.filter(v => v.type === 'auto').length }} registrado{{ vehicles.filter(v => v.type === 'auto').length !== 1 ? 's' : '' }}
              </div>
            </div>
          </button>
          
          <button
            @click="selectedFilter = 'moto'"
            :class="[
              'h-14 px-8 rounded-xl flex items-center space-x-3 transition-all duration-200',
              selectedFilter === 'moto'
                ? 'bg-green-500 text-white shadow-md'
                : 'hover:bg-green-50 text-green-600'
            ]"
          >
            <Bike class="h-6 w-6" />
            <div class="text-left">
              <div class="font-medium">Motos</div>
              <div class="text-xs opacity-80">
                {{ vehicles.filter(v => v.type === 'moto').length }} registrado{{ vehicles.filter(v => v.type === 'moto').length !== 1 ? 's' : '' }}
              </div>
            </div>
          </button>
        </div>
      </div>

      <!-- Título de la sección -->
      <div class="text-center">
        <h2 class="text-xl font-semibold text-slate-800">
          {{ selectedFilter === 'auto' ? 'Mis Autos' : 'Mis Motos' }}
        </h2>
        <p class="text-sm text-slate-600 mt-1">
          {{ filteredVehicles.length }} vehículo{{ filteredVehicles.length !== 1 ? 's' : '' }} registrado{{ filteredVehicles.length !== 1 ? 's' : '' }}
        </p>
      </div>

      <!-- Botón registrar vehículo -->
      <div class="flex justify-center">
        <button
          @click="showRegistrationForm = true"
          :class="[
            'h-14 px-6 border-2 border-dashed rounded-xl flex items-center space-x-3 transition-all duration-200',
            selectedFilter === 'auto'
              ? 'border-blue-300 text-blue-600 hover:bg-blue-50 hover:border-blue-400'
              : 'border-green-300 text-green-600 hover:bg-green-50 hover:border-green-400'
          ]"
        >
          <Plus class="h-5 w-5" />
          <span>Registrar {{ selectedFilter === 'auto' ? 'un auto' : 'una moto' }}</span>
        </button>
      </div>

      <!-- Grid de vehículos -->
      <div v-if="filteredVehicles.length > 0" class="flex flex-wrap gap-4 justify-center">
        <Card
          v-for="vehicle in filteredVehicles"
          :key="vehicle.id"
          class="p-4 bg-gradient-to-br from-white to-slate-50 border-2 hover:border-blue-300 transition-all duration-200 hover:shadow-lg min-w-40 max-w-48"
        >
          <div class="space-y-3">
            <!-- Imagen del vehículo si existe -->
            <div v-if="vehicle.image" class="w-full h-24 rounded-lg overflow-hidden">
              <img 
                :src="vehicle.image" 
                :alt="vehicle.name"
                class="w-full h-full object-cover"
              />
            </div>
            
            <div class="flex items-center justify-between">
              <Car v-if="vehicle.type === 'auto'" class="h-6 w-6 text-blue-600" />
              <Bike v-else class="h-6 w-6 text-green-600" />
              <button
                class="h-8 w-8 hover:bg-slate-100 rounded-full flex items-center justify-center transition"
              >
                <Settings class="h-4 w-4 text-slate-600" />
              </button>
            </div>
            
            <div class="space-y-1">
              <p class="font-medium text-slate-800">{{ vehicle.name }}</p>
              <p class="text-sm text-slate-600 font-mono">{{ vehicle.plate }}</p>
              <p class="text-xs text-slate-500">{{ vehicle.model }}</p>
            </div>
          </div>
        </Card>
      </div>

      <!-- Mensaje cuando no hay vehículos -->
      <div v-if="filteredVehicles.length === 0" class="text-center py-12">
        <div class="inline-block p-6 bg-white/50 rounded-2xl">
          <Car v-if="selectedFilter === 'auto'" class="h-16 w-16 mx-auto text-slate-300 mb-4" />
          <Bike v-else class="h-16 w-16 mx-auto text-slate-300 mb-4" />
          <p class="text-slate-600 mb-2">No tenés {{ selectedFilter === 'auto' ? 'autos' : 'motos' }} registrados</p>
          <p class="text-sm text-slate-500">Registrá tu primer vehículo para comenzar</p>
        </div>
      </div>
    </div>

    <!-- Modal de registro (simplificado) -->
    <div v-if="showRegistrationForm" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/20 backdrop-blur-sm">
      <div class="bg-white rounded-2xl p-6 max-w-md w-full shadow-2xl">
        <h3 class="text-xl font-bold mb-4">Registrar {{ selectedFilter === 'auto' ? 'Auto' : 'Moto' }}</h3>
        <p class="text-slate-600 text-sm mb-6">Formulario de registro en desarrollo</p>
        <button
          @click="showRegistrationForm = false"
          class="w-full bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl transition"
        >
          Cerrar
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { Car, Bike, Plus, Settings } from 'lucide-vue-next'
import Card from '@/components/ui/Card.vue'

defineEmits(['close'])

const selectedFilter = ref('auto')
const showRegistrationForm = ref(false)

// Datos simulados de vehículos
const vehicles = ref([
  { id: '1', type: 'auto', name: 'Mi Auto', plate: 'ABC 123', model: 'Toyota Corolla 2020' },
  { id: '2', type: 'auto', name: 'Auto Familiar', plate: 'XYZ 789', model: 'Honda Civic 2019' },
  { id: '3', type: 'moto', name: 'Mi Moto', plate: 'MOT 456', model: 'Honda Wave 110' },
  { id: '4', type: 'auto', name: 'Auto Trabajo', plate: 'DEF 456', model: 'Ford Focus 2021' }
])

const filteredVehicles = computed(() => {
  return vehicles.value.filter(v => v.type === selectedFilter.value)
})
</script>
