// frontend/src/components/employee/ReservationValidator.vue
<template>
  <div class="space-y-6">
    <div class="bg-white rounded-lg shadow p-6">
      <!-- Header -->
      <div class="flex items-center gap-2 mb-6">
        <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
        </svg>
        <h2 class="text-xl font-semibold text-gray-900">Validador de Reservas</h2>
      </div>

      <!-- Tabs -->
      <div class="mb-6">
        <div class="border-b border-gray-200">
          <nav class="-mb-px flex space-x-8">
            <button
              @click="activeTab = 'numeric'"
              :class="[
                'py-2 px-1 border-b-2 font-medium text-sm transition-colors',
                activeTab === 'numeric' 
                  ? 'border-blue-500 text-blue-600' 
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              ]"
            >
              Código Numérico
            </button>
            <button
              @click="activeTab = 'qr'"
              :class="[
                'py-2 px-1 border-b-2 font-medium text-sm transition-colors',
                activeTab === 'qr' 
                  ? 'border-blue-500 text-blue-600' 
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              ]"
            >
              Código QR
            </button>
          </nav>
        </div>
      </div>

      <!-- Tab Content: Código Numérico -->
      <div v-if="activeTab === 'numeric'" class="space-y-4">
        <div>
          <label for="code" class="block text-sm font-medium text-gray-700 mb-2">
            Ingrese el código de reserva
          </label>
          <div class="flex gap-2">
            <input
              id="code"
              v-model="numericCode"
              type="text"
              placeholder="Ej: 4567"
              @keyup.enter="validateCode"
              class="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
            <button
              @click="validateCode"
              :disabled="!numericCode.trim()"
              class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              Validar
            </button>
          </div>
        </div>
      </div>

      <!-- Tab Content: Código QR -->
      <div v-if="activeTab === 'qr'" class="text-center space-y-4">
        <p class="text-sm text-gray-600">Simulación de escaneo QR</p>
        <button
          @click="simulateQRScan"
          class="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          Simular Escaneo QR
        </button>
        <p class="text-xs text-gray-500">
          En producción, esto activaría la cámara para escanear un código QR real
        </p>
      </div>
    </div>

    <!-- Validation Result -->
    <div v-if="validationResult" class="bg-white rounded-lg shadow p-6">
      <!-- Éxito -->
      <div v-if="validationResult.valid" class="space-y-4">
        <div class="flex items-center gap-2 text-green-700">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span class="font-medium text-lg">Reserva Válida</span>
        </div>
        
        <div class="bg-green-50 p-4 rounded-lg space-y-3">
          <div class="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span class="font-medium text-gray-700">Cliente:</span>
              <span class="ml-2">{{ validationResult.reservation.usuario.nombre }}</span>
            </div>
            <div>
              <span class="font-medium text-gray-700">Placa:</span>
              <span class="ml-2">{{ validationResult.reservation.vehiculo.placa }}</span>
            </div>
            <div>
              <span class="font-medium text-gray-700">Código:</span>
              <span class="ml-2 font-mono">{{ validationResult.reservation.codigo_numerico }}</span>
            </div>
            <div>
              <span class="font-medium text-gray-700">Vehículo:</span>
              <span class="ml-2">{{ validationResult.reservation.vehiculo.modelo }}</span>
            </div>
          </div>
          <div class="pt-2">
            <span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-green-100 text-green-800">
              Reserva Confirmada
            </span>
          </div>
        </div>
      </div>

      <!-- Error -->
      <div v-else class="space-y-4">
        <div class="flex items-center gap-2 text-red-700">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span class="font-medium text-lg">Código Inválido</span>
        </div>
        
        <div class="bg-red-50 p-4 rounded-lg">
          <p class="text-sm text-red-700">
            El código ingresado no corresponde a ninguna reserva válida.
            Verifique el código y vuelva a intentar.
          </p>
        </div>
      </div>
    </div>

    <!-- Instructions -->
    <div class="bg-white rounded-lg shadow p-6">
      <h3 class="font-medium text-gray-900 mb-4">Instrucciones</h3>
      <div class="space-y-2 text-sm text-gray-600">
        <p>• <strong>Código Numérico:</strong> Ingrese el código de 4 dígitos proporcionado al cliente</p>
        <p>• <strong>Código QR:</strong> Use la simulación para probar (en producción usará cámara)</p>
        <p>• Una vez validada la reserva, proceda a asignar un espacio disponible</p>
        <p>• Códigos de prueba válidos: <strong>4567, 8901, 2345</strong></p>
      </div>
    </div>
  </div>
</template>

<script>
import { validateReservation } from '@/services/employeeService';

export default {
  name: 'ReservationValidator',
  data() {
    return {
      activeTab: 'numeric',
      numericCode: '',
      validationResult: null
    };
  },
  methods: {
    async validateCode() {
      if (!this.numericCode.trim()) return;
      
      try {
        const response = await validateReservation(this.numericCode.trim());
        
        if (response.success) {
          this.validationResult = response.data;
          if (response.data.valid) {
            this.numericCode = '';
          }
        }
      } catch (error) {
        console.error('Validation error:', error);
      }
    },
    async simulateQRScan() {
      // Simular escaneo de QR con un código aleatorio
      const mockCodes = ['4567', '8901', '2345', 'INVALID'];
      const randomCode = mockCodes[Math.floor(Math.random() * mockCodes.length)];
      
      this.numericCode = randomCode;
      await this.validateCode();
    }
  }
};
</script>

// Employee Dashboard Module/src/components/ReservationValidator.tsx
import React, { useState, useRef } from 'react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Label } from './ui/label';
import { Badge } from './ui/badge';
import { QrCode, Hash, Camera, CheckCircle, XCircle, Scan } from 'lucide-react';

interface ReservationValidatorProps {
  onValidate: (code: string) => { isValid: boolean; reservation?: any };
}

export function ReservationValidator({ onValidate }: ReservationValidatorProps) {
  const [numericCode, setNumericCode] = useState('');
  const [qrResult, setQrResult] = useState('');
  const [validationResult, setValidationResult] = useState(null);
  const [isScanning, setIsScanning] = useState(false);
  const videoRef = useRef(null);
  const streamRef = useRef(null);

  const handleNumericValidation = () => {
    if (!numericCode.trim()) return;
    
    const result = onValidate(numericCode.trim());
    setValidationResult(result);
    
    if (result.isValid) {
      setNumericCode('');
    }
  };

  const startQRScanning = async () => {
    try {
      setIsScanning(true);
      
      // Simulate QR camera access (in a real app, you'd use a QR library like react-qr-reader)
      const stream = await navigator.mediaDevices.getUserMedia({ 
        video: { facingMode: 'environment' } 
      });
      
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        streamRef.current = stream;
      }
    } catch (error) {
      console.error('Error accessing camera:', error);
      // Simulate QR scan result for demo
      setTimeout(() => {
        simulateQRScan();
      }, 2000);
    }
  };

  const stopQRScanning = () => {
    setIsScanning(false);
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop());
      streamRef.current = null;
    }
  };

  const simulateQRScan = () => {
    // Simulate scanning a QR code with reservation code
    const mockQRCodes = ['4567', '8901', '2345', 'INVALID123'];
    const randomCode = mockQRCodes[Math.floor(Math.random() * mockQRCodes.length)];
    
    setQrResult(randomCode);
    const result = onValidate(randomCode);
    setValidationResult(result);
    stopQRScanning();
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <QrCode className="h-5 w-5" />
            Validador de Reservas
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="numeric" className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="numeric" className="flex items-center gap-2">
                <Hash className="h-4 w-4" />
                Código Numérico
              </TabsTrigger>
              <TabsTrigger value="qr" className="flex items-center gap-2">
                <QrCode className="h-4 w-4" />
                Código QR
              </TabsTrigger>
            </TabsList>
            
            <TabsContent value="numeric" className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="numeric-code">Ingrese el código de reserva</Label>
                <div className="flex gap-2">
                  <Input
                    id="numeric-code"
                    value={numericCode}
                    onChange={(e) => setNumericCode(e.target.value)}
                    placeholder="Ej: 4567"
                    onKeyPress={(e) => e.key === 'Enter' && handleNumericValidation()}
                  />
                  <Button onClick={handleNumericValidation} disabled={!numericCode.trim()}>
                    Validar
                  </Button>
                </div>
              </div>
            </TabsContent>
            
            <TabsContent value="qr" className="space-y-4">
              <div className="text-center space-y-4">
                {!isScanning ? (
                  <div>
                    <Button onClick={startQRScanning} className="flex items-center gap-2">
                      <Camera className="h-4 w-4" />
                      Iniciar Escaneo QR
                    </Button>
                    <p className="text-sm text-gray-600 mt-2">
                      Toque el botón para activar la cámara y escanear un código QR
                    </p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="relative bg-black rounded-lg overflow-hidden">
                      <video
                        ref={videoRef}
                        autoPlay
                        playsInline
                        className="w-full h-64 object-cover"
                      />
                      <div className="absolute inset-0 border-2 border-white opacity-50 rounded-lg">
                        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                          <div className="w-48 h-48 border-2 border-white rounded-lg flex items-center justify-center">
                            <Scan className="h-8 w-8 text-white animate-pulse" />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex gap-2 justify-center">
                      <Button onClick={simulateQRScan} variant="outline">
                        Simular Escaneo
                      </Button>
                      <Button onClick={stopQRScanning} variant="outline">
                        Cancelar
                      </Button>
                    </div>
                  </div>
                )}
                
                {qrResult && (
                  <div className="text-sm text-gray-600">
                    Último código escaneado: <span className="font-mono">{qrResult}</span>
                  </div>
                )}
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* Validation Result */}
      {validationResult && (
        <Card>
          <CardContent className="pt-6">
            {validationResult.isValid ? (
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-green-700">
                  <CheckCircle className="h-5 w-5" />
                  <span className="font-medium">Reserva Válida</span>
                </div>
                
                <div className="bg-green-50 p-4 rounded-lg space-y-2">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="font-medium">Cliente:</span> {validationResult.reservation.customerName}
                    </div>
                    <div>
                      <span className="font-medium">Placa:</span> {validationResult.reservation.vehiclePlate}
                    </div>
                    <div>
                      <span className="font-medium">Código:</span> {validationResult.reservation.code}
                    </div>
                    <div>
                      <span className="font-medium">Duración:</span> {validationResult.reservation.duration} min
                    </div>
                  </div>
                  <div className="pt-2">
                    <Badge variant="secondary" className="bg-green-100 text-green-800">
                      Reserva Confirmada
                    </Badge>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-red-700">
                  <XCircle className="h-5 w-5" />
                  <span className="font-medium">Código Inválido</span>
                </div>
                
                <div className="bg-red-50 p-4 rounded-lg">
                  <p className="text-sm text-red-700">
                    El código ingresado no corresponde a ninguna reserva válida.
                    Verifique el código y vuelva a intentar.
                  </p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Instructions */}
      <Card>
        <CardHeader>
          <CardTitle>Instrucciones</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-gray-600 space-y-2">
          <p>• <strong>Código Numérico:</strong> Ingrese el código de 4 dígitos proporcionado al cliente</p>
          <p>• <strong>Código QR:</strong> Use la cámara para escanear el código QR del cliente</p>
          <p>• Una vez validada la reserva, proceda a asignar un espacio disponible</p>
          <p>• Los códigos de prueba válidos son: 4567, 8901, 2345</p>
        </CardContent>
      </Card>
    </div>
  );
}
